### PR TITLE
add method waitForConnectResult to improve wifi connecting

### PR DESCRIPTION
**Pull request by hasenradball**
# improve Wifi connecting by new method `waitForConnectResult()`
- more or less an copy of the ESP8266 core method
- improves WiFi.begin() handling
- by using this function the connection status is returned very fast
- added illustration example

### CODE REVIEW

**Comment by JAndrassy** [comment]
WiFi.begin is blocking in WiFiNINA and other Arduino WiFi libraries.

**Comment by hasenradball** [comment]
@JAndrassy yes I saw the code, but when I tested  it I reached the fastest connection time with this aproach.

The other solution would be to rework the begin to be able to distinguish between timeout an other wl_status codes.

**Comment by hasenradball** [comment]
With the `begin` you are not able to distinguish between timeout and other codes.
I prepared this modifieg begin also.
I will create a PR to be able to compare.

**Comment by hasenradball** [comment]
@JAndrassy 
See PR #263 for refracture begin methods to improve wifi connecting without a `waitForConnectResult()`method in combination with  connect method without blocking.

**Pull request closed without merging**
