### PR TITLE
Add support for MKR Vidor 4000

### PR DESCRIPTION
**Pull request by sandeepmistry**
cc/ @akash73 @cmaglie

### CODE REVIEW

**Comment by satblip** [comment]
Hi,

I get an error, trying to build my sketch:

```
In file included from /Users/satblip/Library/Arduino15/packages/arduino/hardware/samd_beta/1.6.22/cores/arduino/delay.h:23:0,
                 from /Users/satblip/Library/Arduino15/packages/arduino/hardware/samd_beta/1.6.22/cores/arduino/Arduino.h:81,
                 from /Users/satblip/Github/_arduino/libraries/WiFiNINA/src/utility/spi_drv.cpp:21:
/Users/satblip/Github/_arduino/libraries/WiFiNINA/src/utility/spi_drv.cpp: In static member function 'static void SpiDrv::begin()':
/Users/satblip/Library/Arduino15/packages/arduino/hardware/samd_beta/1.6.22/variants/mkrvidor/variant.h:125:25: error: 'SPIEx' was not declared in this scope
 #define SPIWIFI         SPIEx
                         ^
/Users/satblip/Github/_arduino/libraries/WiFiNINA/src/utility/spi_drv.cpp:81:7: note: in expansion of macro 'SPIWIFI'
       SPIWIFI.begin();
       ^~~~~~~
/Users/satblip/Library/Arduino15/packages/arduino/hardware/samd_beta/1.6.22/variants/mkrvidor/variant.h:125:25: note: suggested alternative: 'SPI1'
 #define SPIWIFI         SPIEx
                         ^
/Users/satblip/Github/_arduino/libraries/WiFiNINA/src/utility/spi_drv.cpp:81:7: note: in expansion of macro 'SPIWIFI'
       SPIWIFI.begin();
       ^~~~~~~
/Users/satblip/Github/_arduino/libraries/WiFiNINA/src/utility/spi_drv.cpp: In static member function 'static void SpiDrv::end()':
/Users/satblip/Library/Arduino15/packages/arduino/hardware/samd_beta/1.6.22/variants/mkrvidor/variant.h:125:25: error: 'SPIEx' was not declared in this scope
 #define SPIWIFI         SPIEx
                         ^
/Users/satblip/Github/_arduino/libraries/WiFiNINA/src/utility/spi_drv.cpp:110:5: note: in expansion of macro 'SPIWIFI'
     SPIWIFI.end();
     ^~~~~~~
/Users/satblip/Library/Arduino15/packages/arduino/hardware/samd_beta/1.6.22/variants/mkrvidor/variant.h:125:25: note: suggested alternative: 'SPI1'
 #define SPIWIFI         SPIEx
                         ^
/Users/satblip/Github/_arduino/libraries/WiFiNINA/src/utility/spi_drv.cpp:110:5: note: in expansion of macro 'SPIWIFI'
     SPIWIFI.end();
     ^~~~~~~
/Users/satblip/Github/_arduino/libraries/WiFiNINA/src/utility/spi_drv.cpp: In static member function 'static void SpiDrv::spiSlaveSelect()':
/Users/satblip/Library/Arduino15/packages/arduino/hardware/samd_beta/1.6.22/variants/mkrvidor/variant.h:125:25: error: 'SPIEx' was not declared in this scope
 #define SPIWIFI         SPIEx
                         ^
/Users/satblip/Github/_arduino/libraries/WiFiNINA/src/utility/spi_drv.cpp:117:5: note: in expansion of macro 'SPIWIFI'
     SPIWIFI.beginTransaction(SPISettings(8000000, MSBFIRST, SPI_MODE0));
     ^~~~~~~
/Users/satblip/Library/Arduino15/packages/arduino/hardware/samd_beta/1.6.22/variants/mkrvidor/variant.h:125:25: note: suggested alternative: 'SPI1'
 #define SPIWIFI         SPIEx
                         ^
/Users/satblip/Github/_arduino/libraries/WiFiNINA/src/utility/spi_drv.cpp:117:5: note: in expansion of macro 'SPIWIFI'
     SPIWIFI.beginTransaction(SPISettings(8000000, MSBFIRST, SPI_MODE0));
     ^~~~~~~
/Users/satblip/Github/_arduino/libraries/WiFiNINA/src/utility/spi_drv.cpp: In static member function 'static void SpiDrv::spiSlaveDeselect()':
/Users/satblip/Library/Arduino15/packages/arduino/hardware/samd_beta/1.6.22/variants/mkrvidor/variant.h:125:25: error: 'SPIEx' was not declared in this scope
 #define SPIWIFI         SPIEx
                         ^
/Users/satblip/Github/_arduino/libraries/WiFiNINA/src/utility/spi_drv.cpp:129:5: note: in expansion of macro 'SPIWIFI'
     SPIWIFI.endTransaction();
     ^~~~~~~
/Users/satblip/Library/Arduino15/packages/arduino/hardware/samd_beta/1.6.22/variants/mkrvidor/variant.h:125:25: note: suggested alternative: 'SPI1'
 #define SPIWIFI         SPIEx
                         ^
/Users/satblip/Github/_arduino/libraries/WiFiNINA/src/utility/spi_drv.cpp:129:5: note: in expansion of macro 'SPIWIFI'
     SPIWIFI.endTransaction();
     ^~~~~~~
/Users/satblip/Github/_arduino/libraries/WiFiNINA/src/utility/spi_drv.cpp: In static member function 'static char SpiDrv::spiTransfer(char)':
/Users/satblip/Library/Arduino15/packages/arduino/hardware/samd_beta/1.6.22/variants/mkrvidor/variant.h:125:25: error: 'SPIEx' was not declared in this scope
 #define SPIWIFI         SPIEx
                         ^
/Users/satblip/Github/_arduino/libraries/WiFiNINA/src/utility/spi_drv.cpp:135:19: note: in expansion of macro 'SPIWIFI'
     char result = SPIWIFI.transfer(data);
                   ^~~~~~~
/Users/satblip/Library/Arduino15/packages/arduino/hardware/samd_beta/1.6.22/variants/mkrvidor/variant.h:125:25: note: suggested alternative: 'SPI1'
 #define SPIWIFI         SPIEx
                         ^
/Users/satblip/Github/_arduino/libraries/WiFiNINA/src/utility/spi_drv.cpp:135:19: note: in expansion of macro 'SPIWIFI'
     char result = SPIWIFI.transfer(data);
                   ^~~~~~~
```

Any idea?

**Comment by sandeepmistry** [comment]
Hi @satblip,

This change needs to be accompanied by some changes to the SAMD beta core. @cmaglie will release an update of the beta core and let you know here when it is available.

**Comment by satblip** [comment]
HI @sandeepmistry,

Thanks for the info ;-)

**Comment by sandeepmistry** [comment]
Hi @satblip,

The required changes to use this library have been release, please read http://forum.arduino.cc/index.php?topic=563513.0 for more details.

**Comment by satblip** [comment]
@sandeepmistry Cool thanks, I'll try to check that this evening :)

**Comment by satblip** [comment]
@sandeepmistry checked and approved. it worked like a charm ;)

**Pull request merged**
