### PR TITLE
Add non blocking WiFi.connect() method

### PR DESCRIPTION
**Pull request by hasenradball**
# why to update/benefits
- with this rework a better and faster wifi connect is possible, because connect don't wait for final result.
  Connecting goes on in background, so other tasks can be done during connecting.

With this approach we introduce the methods `connect` which is an non blocking wifi connect method

Now we can start the wifi connection without blocking..

## Changes in methods
- add new non blocking connect method

### tested on

Arduino Nano 33 IOT

### CODE REVIEW

**Comment by JAndrassy** [comment]
if I want wait for connection result I can use `begin`. so waitForConnectionResult is not useful. esp8266 and esp32 have waitForConnectionResult because their `begin` is not blocking.
`connect` is useful if `state()` is checked later in loop() to do some communication over WiFi

**Comment by hasenradball** [comment]
@JAndrassy 
If you don`t see ann benefit for waitForConnect then please look at PR #263.
With this approach there are indroduced small benefits.
Thanks
Frank

**Comment by JAndrassy** [comment]
@263 changes `begin`. how is it related to waitForConnectResult?

**Comment by hasenradball** [comment]
@JAndrassy 
It is related in this way:
- return immediately if connected
- is able to return -1 as inicate if timeout occurs

please take two min. to read the explanations in #263 .

If waitForConnectResult is no way for you, maybee we can improve the begin methods slightly.
😊

**Comment by JAndrassy** [comment]
I have no objection to `connect`.

**Comment by hasenradball** [comment]
@JAndrassy  maybee you looked in the wrong code.

Chances in begin are located in #263 .

And one hint to the benefit if a non blocking connect!
Why to wait if wifi is connected?
Use a non blocking connect method an let the wifi connecting in background.
Do meanwhile other stuff in setup.
And check the connection status at the end of setup.

**Comment by JAndrassy** [comment]
again. I have no objection to your `connect`.

I responded about begin to your "maybee we can improve the begin methods slightly."

**Comment by hasenradball** [comment]
@JAndrassy 
Thanks for your reply.
I will rework it to add only the necessary changes.
Will you add the connect method from the existing branch to the master to be able to be used?

**Comment by JAndrassy** [comment]
I am just a contributor . I would like my own PR be merged.

**Comment by hasenradball** [comment]
@JAndrassy can we then move further discussions for `begin` to #263 ?

**Comment by hasenradball** [comment]
Hi @JAndrassy,
I removed the `waitForConnectResult`, now only the non blocking connect method added here.

**Comment by JAndrassy** [comment]
I think you would achieve same as this `connect` with setting timeout to 0 for `begin`

**Comment by hasenradball** [comment]
@JAndrassy 

Could be, BUT if you looked at the code, the value of Timeout is hardcoded!
And if I want to use an `non blocking connect method`, I don't want to step into the src file first and make changes in the constructor!

Thats's not the way of smart software development, right?

 
Bildschirmfoto 2023-11-11 um 19 18 47

**Comment by JAndrassy** [comment]
there is WiFi.setTimeout

**Comment by hasenradball** [comment]
Yes, you are right I saw it in the same time you wrote.

Bildschirmfoto 2023-11-11 um 20 09 47

Is there an big point to add the connect methods?

I actually had an idea about simplify the connect methods by using the `setTimeout()` method like:

Bildschirmfoto 2023-11-11 um 20 17 04

**Comment by hasenradball** [comment]
@JAndrassy using `setTimeout(0)`before `begin()`works fine.
So I would say there is no real need to introduce a `connect()`method.

**Pull request closed without merging**
