### PR TITLE
 Added new example and documentation examples changes

### PR DESCRIPTION
**Pull request by Rocketct**
- Added check firmware version example, CheckFirmwareVersion.ino
- Modified the sketchs documentation , it was alligned with board module name

### CODE REVIEW

**Comment by Rocketct** [comment]
@sandeepmistry check if ok.

**Comment by sandeepmistry** [comment]
Resolves #22 and #25.

**Comment by Rocketct** [comment]
@akash73

**Comment by akash73** [comment]
LGTM

**Pull request merged**
