### PR TITLE
Refactor WiFi.begin() methods to improve Wifi connecting

### PR DESCRIPTION
**Pull request by hasenradball**
# why to improve?
With this rework the following benefits added:
- return value of int16_t
- return of `-1` is possible => indicated timeout 

## tested on
- Arduino Nano 33 IOT

### CODE REVIEW

**Comment by JAndrassy** [comment]
I don't see the change. formatting changed. `while` instead `for` and `return` instead of `break`.  I don't see what it does differently.
and the connection time is same too.

**Comment by hasenradball** [comment]
@JAndrassy then you should have a closer look.
see the `status =-1;`

**Comment by JAndrassy** [comment]
so yes, but why the other changes in the code? you must adapt to code style of the original source code and not change more lines than needed.

**Comment by hasenradball** [comment]
Hi @JAndrassy,

added now only the necessary stuff to improve the existing `WiFi.begin()` methods.
Here the summary:

- return type changed to `int16_t` due to NO_SHIELD needs value 255
- changed variable `status` also to `int16_t`
- return if connected directly => return status 
- added `status = -1;` in case of timeout

**Comment by JAndrassy** [comment]
looks much better.

**Comment by hasenradball** [comment]
@JAndrassy
one hint why I want to change the loop from `for` to `while` was the while loop is much faster than the for loop.

**Comment by JAndrassy** [comment]
that would lead me to investigate if it is really the same loop logic. I trust C++ compiler to generate the same assembly from both cases.

**Comment by hasenradball** [comment]
Hi @JAndrassy,

This can easily checked normally by [godbold](https://godbolt.org/).

From my expirience as SW Developer I have often seen that while is faster than for loop.
Thats the reason I suggested this.

If thats the case you will get 30% more performance for free.

**Comment by hasenradball** [comment]
Hi @JAndrassy,

I made some screenshots for you.

a) First example `while` loop:
Bildschirmfoto 2023-11-12 um 20 16 06



==> You see 15 lines of Assembler instructions.


b) Second Example `for` loop:
Bildschirmfoto 2023-11-12 um 20 19 45


I hope I compared apples with apples.
It seems to be the same code. :-)

**Pull request closed without merging**
